[package]
name = "frqstbite/walmartmm2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Knit = "sleitnick/knit@^1.5"